[gcp_service_account]
type = "service_account"
project_id = "analog-arbor-464806-n7"
private_key_id = "d65258858659ff9642226b40122d8ba5e46179a1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASC...
...your real key continues here...
-----END PRIVATE KEY-----"""
client_email = "129249538815-compute@developer.gserviceaccount.com"
client_id = "111938097483973761044"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/129249538815-compute%40developer.gserviceaccount.com"
universe_domain = "googleapis.com"
